# Generated by Django 3.1.7 on 2021-03-27 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date',
        ),
    ]
